### ISSUE TITLE
Replacing Certs don't work - Task is skipping

### ISSUE THREAD

**Issue by DirectorSloan** [idiv-biodiversity/ssl-certificates#2] opened 2021-09-10 12:21 UTC
Don't work when updating certs.

What I did:

- replaced the cert file in the host_vars of the $HOST
- replaced the key in vault of the $HOST
- run `ansible-playbook interactive.yml -l $HOST -t ssl-certificates -b -K --ask-vault-pass`

What happened:

- the TASK deploy certificate is skipping.

Found nothing in README.md

**Comment by DirectorSloan** [comment] 2021-09-10 12:22
Output mit `-vvv`:

"skip_reason": "Conditional result was False"

**Comment by dirks** [comment] 2021-09-14 18:33
Cannot reproduce. Can you provide
- a minimal example including (censored) variable definition
-  the actual but censored output of the role tasks during the play
- and if not in the role tasks the tasks that outputs the "skip_reason": "Conditional result was False"?

This sounds a bit like a stray variable definition somewhere. You might want to ensure that the variable value evaluated is the one you intend.  This might be helpful:
- [Variable precedence](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#ansible-variable-precedence)
- `grep -rn 'ssl_certificates:' $your-ansible-dir $your-other-ansible-dir-included-in-ansible.cfg-but-forgotten-by-now` :wink: 
- run the playbook with the `--extra-vars "ssl_certificates=…"` to get highest variable priority. Note that you can specify a file which has the variable definition see https://ttl255.com/ansible-pass-extra-variables-to-playbook/

edit: the deploy certificate task has no conditional: https://github.com/idiv-biodiversity/ansible-role-ssl-certificates/blob/master/tasks/main.yml

**Comment by wookietreiber** [comment] 2023-07-05 07:20
closing, will archive repo. we currently aren't using the role and we can't keep on maintaining it.

**Closed as completed by wookietreiber** 2023-07-05 07:20 UTC
